from app.modules.opportunities.models import Opportunity
from app.shared.base_repository import BaseRepository


class OpportunityRepository(BaseRepository):
    """
    Repository for Opportunity persistence and lookup.

    Responsibilities:
        - Opportunity-specific database queries
        - identity lookups
        - search-index lookups

    It does not:
        - scrape external sources
        - parse source content
        - map scraper data
        - generate search aliases
        - decide publication status
    """

    model = Opportunity

    # =========================================================
    # IDENTITY
    # =========================================================

    async def find_by_slug(
        self,
        slug: str,
    ):
        """
        Find an opportunity by its canonical slug.

        Example:
            berliner-antike-kolleg-daad-phd-scholarships-2027
        """

        return await self.first(
            filters={
                "slug": slug,
            }
        )

    async def find_by_source_url(
        self,
        source_url: str,
    ):
        """
        Find an opportunity by its exact external source URL.

        This is the strongest identity lookup for scraped
        opportunities because the source URL points to the
        exact external opportunity page.
        """

        return await self.first(
            filters={
                "source_url": source_url,
            }
        )

    async def find_by_source_and_slug(
        self,
        *,
        source_name: str,
        slug: str,
    ):
        """
        Find an opportunity using a source-scoped canonical slug.

        This prevents opportunities from different sources with
        similar titles from being treated as the same record.
        """

        return await self.first(
            filters={
                "source_name": source_name,
                "slug": slug,
            }
        )

    # =========================================================
    # SEARCH INDEX
    # =========================================================

    async def find_by_search_term(
        self,
        term: str,
    ):
        """
        Find opportunities using the search alias index.

        `slug_list` is NOT a historical slug list.

        It contains normalized search aliases generated by
        SearchTermsBuilder.

        Examples:

            "phd"
            "usa"
            "software-engineering"
            "remote"
            "scholarship"
            "japan"

        QueryEngine delegates this search to SearchBuilder,
        which supports JSON fields.
        """

        return await self.list(
            search=term,
            search_fields=[
                "slug_list",
            ],
        )

