"""update orgs models

Revision ID: 48d1b7d55e1a
Revises: cb47a41d0ecb
Create Date: 2026-08-31 13:12:30.587287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d1b7d55e1a'
down_revision: Union[str, Sequence[str], None] = 'cb47a41d0ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership_roles', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_membership_roles_company_id'), 'membership_roles', ['company_id'], unique=False)
    op.create_foreign_key(None, 'membership_roles', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('membership_type_assignments', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_membership_type_assignments_company_id'), 'membership_type_assignments', ['company_id'], unique=False)
    op.create_foreign_key(None, 'membership_type_assignments', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'membership_type_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_membership_type_assignments_company_id'), table_name='membership_type_assignments')
    op.drop_column('membership_type_assignments', 'company_id')
    op.drop_constraint(None, 'membership_roles', type_='foreignkey')
    op.drop_index(op.f('ix_membership_roles_company_id'), table_name='membership_roles')
    op.drop_column('membership_roles', 'company_id')
    # ### end Alembic commands ###
