"""update catalog models

Revision ID: cb47a41d0ecb
Revises: 7dbaee33358c
Create Date: 2026-08-30 10:24:42.852766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb47a41d0ecb'
down_revision: Union[str, Sequence[str], None] = '7dbaee33358c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_options', sa.Column('company_id', sa.UUID(), nullable=False))
    op.alter_column('product_options', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_product_options_product_id'), table_name='product_options')
    op.drop_constraint(op.f('uq_product_option_product_name'), 'product_options', type_='unique')
    op.create_index(op.f('ix_product_options_company_id'), 'product_options', ['company_id'], unique=False)
    op.create_unique_constraint('uq_product_option_company_code', 'product_options', ['company_id', 'code'])
    op.drop_constraint(op.f('product_options_product_id_fkey'), 'product_options', type_='foreignkey')
    op.create_foreign_key(None, 'product_options', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product_options', 'product_id')
    op.drop_column('product_options', 'sort_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_options', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_options', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_options', type_='foreignkey')
    op.create_foreign_key(op.f('product_options_product_id_fkey'), 'product_options', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_product_option_company_code', 'product_options', type_='unique')
    op.drop_index(op.f('ix_product_options_company_id'), table_name='product_options')
    op.create_unique_constraint(op.f('uq_product_option_product_name'), 'product_options', ['product_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_product_options_product_id'), 'product_options', ['product_id'], unique=False)
    op.alter_column('product_options', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('product_options', 'company_id')
    # ### end Alembic commands ###
